### ISSUE TITLE
Add option for cronjob.

### ISSUE THREAD

**Issue by ghost** [hexonet/whmcs-ispapi-pricingimporter#57]
I think it would be usefull to add an option for cronjobs, so the prices can be updated on a schedule + new domains can be automatically added.

**Comment by papakai** [comment]
Thanks for pointing out on that, we have this already on our to do list. We plan to rewrite the picing importer module from scratch in the next months and to include as many customer requests as possible.
I leave this issue open and will let you know when released.

**Comment by papakai** [comment]
we starting working on a completely new module covering multiple things at once:
* pricing import (with patches and features included reported/requested by our customers)
* product import
* configuration import/wizard
* eventually a kind of issue checker part

 we will let you know when done. for now we can not provide an ETA.

**Comment by papakai** [comment]
fyi: We released a new version of our registrar module (find it [here](https://github.com/hexonet/whmcs-ispapi-registrar/releases)) to support the new `TLD & Pricing Sync` Feature coming with WHMCS 7.10 (currently in unstable RC2). We expect further updates related to that feature, so subscribe to the releases of our registrar module to stay informed.

Some gathered documentation available [here](https://github.com/hexonet/whmcs-ispapi-registrar/wiki/FAQs#55-do-you-support-tld--pricing-sync-mechanism-shipped-with-whmcs-710).

I think this is in general what you were looking for.
