### ISSUE TITLE
Only import 1 year price

### ISSUE THREAD

**Issue by domaingood** [hexonet/whmcs-ispapi-pricingimporter#87]
Only import 1 year price
We need import 1-10 years price imported. Otherwise it useless

**Comment by papakai** [comment]
@domaingood 

Thanks for bringing this up. We are already working on a full review of the pricing importer, but we cannot provide you an ETA. It will definitely take some time until we can provide this.
We are realizing this as new module that includes multiple things:
* configuration import / wizard
* pricing import (including fixes and features reported/requested by our customers)
* product import
* eventually a kind of issue checker in addition

You can imagine that this needs quite a lot of development time, but also effort to test things.
Your feature request is already known to us, will be included in this new module.

Thanks for getting in touch with us and thanks for that feature request.
