### ISSUE TITLE
EU pricing 

### ISSUE THREAD

**Issue by hilbily852** [hexonet/whmcs-ispapi-pricingimporter#91]
The pricing Import works great 

But is there anyway for it to set to Wu pricing and add tax to price or not possible as prices listed will.be wrong cost price

**Comment by papakai** [comment]
@hilbily852 as the README.md points out: the pricing importer module is to be seen as **deprecated**. Please check the `Registrar TLD Sync` Feature of WHMCS 7.10 which you can find under `Utilities` in the WHMCS Admin Area. We have integrated this feature also into our registrar module.

The `Registrar TLD Sync` is the WHMCS built-in solution for pricing import and therefore replaces our module.

Closing this issue therefore. Let me know if that helped and feel free to follow-up if not.
To be honest I couldn't understand what `Wu pricing` means, but finally it wouldn't change things.

HTH!

**Comment by papakai** [comment]
Just a short additional note about taxes: IMO taxes are not part of the TLD prices, but definitely part of the invoices and probably also the output in shopping cart. To get an in-depth clarification and explanation around that topic, I suggest to get in touch with the WHMCS team then. I can just ensure from my side that we were never in touch with taxes when it comes to importing prices.
Taxes are always playing a role within registration/renewal/transfer process and finally being added to the configured prices.
